//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nehta.SMD2010.TRR
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.electronichealth.net.au/smd/svc/TransportResponseRetrieval/2010")]
    public partial class RemoveErrorType
    {
        
        private RemoveErrorCodeType errorCodeField;
        
        private string messageField;
        
        private string responseIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RemoveErrorCodeType errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=2)]
        public string responseId
        {
            get
            {
                return this.responseIdField;
            }
            set
            {
                this.responseIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.electronichealth.net.au/smd/svc/TransportResponseRetrieval/2010")]
    public enum RemoveErrorCodeType
    {
        
        /// <remarks/>
        unknownResponse,
        
        /// <remarks/>
        unknownOrganisation,
        
        /// <remarks/>
        hasNotBeenRetrieved,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.electronichealth.net.au/smd/svc/TransportResponseRetrieval/2010")]
    public partial class RemoveResultType
    {
        
        private string responseIdField;
        
        private RemoveStatusType statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=0)]
        public string responseId
        {
            get
            {
                return this.responseIdField;
            }
            set
            {
                this.responseIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public RemoveStatusType status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.electronichealth.net.au/smd/svc/TransportResponseRetrieval/2010")]
    public enum RemoveStatusType
    {
        
        /// <remarks/>
        ok,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.electronichealth.net.au/wsp/xsd/StandardError/2010")]
    public partial class StandardErrorType
    {
        
        private StandardErrorCodeType errorCodeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public StandardErrorCodeType errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.electronichealth.net.au/wsp/xsd/StandardError/2010")]
    public enum StandardErrorCodeType
    {
        
        /// <remarks/>
        servicePermanentUnavailable,
        
        /// <remarks/>
        serviceTemporaryUnavailable,
        
        /// <remarks/>
        certificateSkiMissing,
        
        /// <remarks/>
        certificateKeyUsage,
        
        /// <remarks/>
        invalidCredentials,
        
        /// <remarks/>
        notAuthenticated,
        
        /// <remarks/>
        notAuthorised,
        
        /// <remarks/>
        badParam,
        
        /// <remarks/>
        badlyFormedMsg,
        
        /// <remarks/>
        badTimestamp,
        
        /// <remarks/>
        badSignature,
        
        /// <remarks/>
        badEncryption,
        
        /// <remarks/>
        badSigEncOrder,
        
        /// <remarks/>
        badCertificateTransmitted,
        
        /// <remarks/>
        badWsaAction,
        
        /// <remarks/>
        badWsaMessageId,
        
        /// <remarks/>
        badWsaTo,
        
        /// <remarks/>
        badAlgorithmDataEncryption,
        
        /// <remarks/>
        badAlgorithmKeyEncryption,
        
        /// <remarks/>
        badAlgorithmC14N,
        
        /// <remarks/>
        badAlgorithmDigest,
        
        /// <remarks/>
        badAlgorithmSignature,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.electronichealth.net.au/smd/svc/TransportResponseRetrieval/2010")]
    public partial class RetrieveErrorType
    {
        
        private RetrieveErrorCodeType errorCodeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RetrieveErrorCodeType errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.electronichealth.net.au/smd/svc/TransportResponseRetrieval/2010")]
    public enum RetrieveErrorCodeType
    {
        
        /// <remarks/>
        unknownOrganisation,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ns.electronichealth.net.au/smd/svc/TransportResponseRetrieval/2010", ConfigurationName="Nehta.SMD2010.TRR.TransportResponseRetrieval")]
    public interface TransportResponseRetrieval
    {
        
        // CODEGEN: Generating message contract since the operation remove is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ns.electronichealth.net.au/smd/svc/TransportResponseRetrieval/2010/Transpo" +
            "rtResponseRetrieval/removeRequest", ReplyAction="http://ns.electronichealth.net.au/smd/svc/TransportResponseRetrieval/2010/Transpo" +
            "rtResponseRetrieval/removeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Nehta.SMD2010.TRR.RemoveErrorType), Action="http://ns.electronichealth.net.au/smd/svc/TransportResponseRetrieval/2010/Transpo" +
            "rtResponseRetrieval/remove/Fault/removeError", Name="removeError")]
        [System.ServiceModel.FaultContractAttribute(typeof(Nehta.SMD2010.TRR.StandardErrorType), Action="http://ns.electronichealth.net.au/smd/svc/TransportResponseRetrieval/2010/Transpo" +
            "rtResponseRetrieval/remove/Fault/standardError", Name="standardError", Namespace="http://ns.electronichealth.net.au/wsp/xsd/StandardError/2010")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Nehta.SMD2010.TRR.removeResponse remove(Nehta.SMD2010.TRR.removeRequest request);
        
        // CODEGEN: Generating message contract since the operation retrieve is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ns.electronichealth.net.au/smd/svc/TransportResponseRetrieval/2010/Transpo" +
            "rtResponseRetrieval/retrieveRequest", ReplyAction="http://ns.electronichealth.net.au/smd/svc/TransportResponseRetrieval/2010/Transpo" +
            "rtResponseRetrieval/retrieveResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Nehta.SMD2010.TRR.RetrieveErrorType), Action="http://ns.electronichealth.net.au/smd/svc/TransportResponseRetrieval/2010/Transpo" +
            "rtResponseRetrieval/retrieve/Fault/retrieveError", Name="retrieveError")]
        [System.ServiceModel.FaultContractAttribute(typeof(Nehta.SMD2010.TRR.StandardErrorType), Action="http://ns.electronichealth.net.au/smd/svc/TransportResponseRetrieval/2010/Transpo" +
            "rtResponseRetrieval/retrieve/Fault/standardError", Name="standardError", Namespace="http://ns.electronichealth.net.au/wsp/xsd/StandardError/2010")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Nehta.SMD2010.TRR.retrieveResponse1 retrieve(Nehta.SMD2010.TRR.retrieveRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ns.electronichealth.net.au/smd/svc/TransportResponseRetrieval/2010")]
    public partial class remove
    {
        
        private bool forceField;
        
        private string organisationField;
        
        private string[] responseIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool force
        {
            get
            {
                return this.forceField;
            }
            set
            {
                this.forceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=1)]
        public string organisation
        {
            get
            {
                return this.organisationField;
            }
            set
            {
                this.organisationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("responseId", DataType="anyURI", Order=2)]
        public string[] responseId
        {
            get
            {
                return this.responseIdField;
            }
            set
            {
                this.responseIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class removeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ns.electronichealth.net.au/smd/svc/TransportResponseRetrieval/2010", Order=0)]
        public Nehta.SMD2010.TRR.remove remove;
        
        public removeRequest()
        {
        }
        
        public removeRequest(Nehta.SMD2010.TRR.remove remove)
        {
            this.remove = remove;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class removeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="removeResponse", Namespace="http://ns.electronichealth.net.au/smd/svc/TransportResponseRetrieval/2010", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("result", IsNullable=false)]
        public RemoveResultType[] removeResponse1;
        
        public removeResponse()
        {
        }
        
        public removeResponse(RemoveResultType[] removeResponse1)
        {
            this.removeResponse1 = removeResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ns.electronichealth.net.au/smd/svc/TransportResponseRetrieval/2010")]
    public partial class retrieve
    {
        
        private string organisationField;
        
        private bool allAvailableField;
        
        private int limitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=0)]
        public string organisation
        {
            get
            {
                return this.organisationField;
            }
            set
            {
                this.organisationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool allAvailable
        {
            get
            {
                return this.allAvailableField;
            }
            set
            {
                this.allAvailableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int limit
        {
            get
            {
                return this.limitField;
            }
            set
            {
                this.limitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ns.electronichealth.net.au/smd/svc/TransportResponseRetrieval/2010")]
    public partial class retrieveResponse
    {
        
        private TransportResponseListType listField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TransportResponseListType list
        {
            get
            {
                return this.listField;
            }
            set
            {
                this.listField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.electronichealth.net.au/smd/svc/TransportResponseRetrieval/2010")]
    public partial class TransportResponseListType
    {
        
        private int totalNumberAvailableField;
        
        private TransportResponseType[] responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int totalNumberAvailable
        {
            get
            {
                return this.totalNumberAvailableField;
            }
            set
            {
                this.totalNumberAvailableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("response", Order=1)]
        public TransportResponseType[] response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.electronichealth.net.au/smd/xsd/TransportResponse/2010")]
    public partial class TransportResponseType
    {
        
        private TransportResponseMetadataType metadataField;
        
        private DeliveryResponseType deliveryResponseField;
        
        private bool finalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TransportResponseMetadataType metadata
        {
            get
            {
                return this.metadataField;
            }
            set
            {
                this.metadataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public DeliveryResponseType deliveryResponse
        {
            get
            {
                return this.deliveryResponseField;
            }
            set
            {
                this.deliveryResponseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool final
        {
            get
            {
                return this.finalField;
            }
            set
            {
                this.finalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.electronichealth.net.au/smd/xsd/TransportResponse/2010")]
    public partial class TransportResponseMetadataType
    {
        
        private System.DateTime transportResponseTimeField;
        
        private string responseIdField;
        
        private string sourceOrganisationField;
        
        private string serviceCategoryField;
        
        private string invocationIdField;
        
        private string receiverOrganisationField;
        
        private string senderOrganisationField;
        
        private OtherTransportMetadataEntryType[] otherTransportMetadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime transportResponseTime
        {
            get
            {
                return this.transportResponseTimeField;
            }
            set
            {
                this.transportResponseTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=1)]
        public string responseId
        {
            get
            {
                return this.responseIdField;
            }
            set
            {
                this.responseIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=2)]
        public string sourceOrganisation
        {
            get
            {
                return this.sourceOrganisationField;
            }
            set
            {
                this.sourceOrganisationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=3)]
        public string serviceCategory
        {
            get
            {
                return this.serviceCategoryField;
            }
            set
            {
                this.serviceCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=4)]
        public string invocationId
        {
            get
            {
                return this.invocationIdField;
            }
            set
            {
                this.invocationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=5)]
        public string receiverOrganisation
        {
            get
            {
                return this.receiverOrganisationField;
            }
            set
            {
                this.receiverOrganisationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=6)]
        public string senderOrganisation
        {
            get
            {
                return this.senderOrganisationField;
            }
            set
            {
                this.senderOrganisationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("otherTransportMetadata", Order=7)]
        public OtherTransportMetadataEntryType[] otherTransportMetadata
        {
            get
            {
                return this.otherTransportMetadataField;
            }
            set
            {
                this.otherTransportMetadataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.electronichealth.net.au/smd/xsd/SealedMessage/2010")]
    public partial class OtherTransportMetadataEntryType
    {
        
        private string metadataTypeField;
        
        private object metadataValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=0)]
        public string metadataType
        {
            get
            {
                return this.metadataTypeField;
            }
            set
            {
                this.metadataTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public object metadataValue
        {
            get
            {
                return this.metadataValueField;
            }
            set
            {
                this.metadataValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.electronichealth.net.au/smd/xsd/TransportResponse/2010")]
    public partial class DeliveryResponseType
    {
        
        private ResponseClassType responseClassField;
        
        private string responseCodeField;
        
        private string messageField;
        
        private byte[] digestValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResponseClassType responseClass
        {
            get
            {
                return this.responseClassField;
            }
            set
            {
                this.responseClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=1)]
        public string responseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=3)]
        public byte[] digestValue
        {
            get
            {
                return this.digestValueField;
            }
            set
            {
                this.digestValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.electronichealth.net.au/smd/xsd/TransportResponse/2010")]
    public enum ResponseClassType
    {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Information,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        Error,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class retrieveRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ns.electronichealth.net.au/smd/svc/TransportResponseRetrieval/2010", Order=0)]
        public Nehta.SMD2010.TRR.retrieve retrieve;
        
        public retrieveRequest()
        {
        }
        
        public retrieveRequest(Nehta.SMD2010.TRR.retrieve retrieve)
        {
            this.retrieve = retrieve;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class retrieveResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ns.electronichealth.net.au/smd/svc/TransportResponseRetrieval/2010", Order=0)]
        public Nehta.SMD2010.TRR.retrieveResponse retrieveResponse;
        
        public retrieveResponse1()
        {
        }
        
        public retrieveResponse1(Nehta.SMD2010.TRR.retrieveResponse retrieveResponse)
        {
            this.retrieveResponse = retrieveResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface TransportResponseRetrievalChannel : Nehta.SMD2010.TRR.TransportResponseRetrieval, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class TransportResponseRetrievalClient : System.ServiceModel.ClientBase<Nehta.SMD2010.TRR.TransportResponseRetrieval>, Nehta.SMD2010.TRR.TransportResponseRetrieval
    {
        
        public TransportResponseRetrievalClient()
        {
        }
        
        public TransportResponseRetrievalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public TransportResponseRetrievalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public TransportResponseRetrievalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public TransportResponseRetrievalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nehta.SMD2010.TRR.removeResponse Nehta.SMD2010.TRR.TransportResponseRetrieval.remove(Nehta.SMD2010.TRR.removeRequest request)
        {
            return base.Channel.remove(request);
        }
        
        public RemoveResultType[] remove(Nehta.SMD2010.TRR.remove remove1)
        {
            Nehta.SMD2010.TRR.removeRequest inValue = new Nehta.SMD2010.TRR.removeRequest();
            inValue.remove = remove1;
            Nehta.SMD2010.TRR.removeResponse retVal = ((Nehta.SMD2010.TRR.TransportResponseRetrieval)(this)).remove(inValue);
            return retVal.removeResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nehta.SMD2010.TRR.retrieveResponse1 Nehta.SMD2010.TRR.TransportResponseRetrieval.retrieve(Nehta.SMD2010.TRR.retrieveRequest request)
        {
            return base.Channel.retrieve(request);
        }
        
        public Nehta.SMD2010.TRR.retrieveResponse retrieve(Nehta.SMD2010.TRR.retrieve retrieve1)
        {
            Nehta.SMD2010.TRR.retrieveRequest inValue = new Nehta.SMD2010.TRR.retrieveRequest();
            inValue.retrieve = retrieve1;
            Nehta.SMD2010.TRR.retrieveResponse1 retVal = ((Nehta.SMD2010.TRR.TransportResponseRetrieval)(this)).retrieve(inValue);
            return retVal.retrieveResponse;
        }
    }
}
